\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item When conducting the work of Lab 11, we conducted the test that uses the
Central Limit Theorem even though the sample size was ``small" (i.e., $n<30$).
It turns out, that how ``far off" the $t$-test is can be computed using
a first-order Edgeworth approximation for the error. Below, we will do this 
for the the further observations.
\begin{enumerate}
  \item \cite{Boos00} note that 
  \begin{align*}
    P(T \leq t) \approx F_Z(t) + \underbrace{\frac{\text{skew}}{\sqrt{n}} \frac{(2t^2+1)}{6} f_Z(t)}_{\textrm{error}},
  \end{align*}
  where $f_Z(\cdot)$ and $F_Z(\cdot)$ are the Gaussian PDF and CDF and skew is the
  skewness of the data. What is the potential error in the computation of the 
  $p$-value when testing $H_0: \mu_X=0; H_a: \mu_X<0$ using the zebra finch further data?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{data} \hlkwb{<-} \hlkwd{read_csv}\hldef{(}\hlsng{"zebrafinches.csv"}\hldef{)}

\hldef{mu0} \hlkwb{<-} \hlnum{0}
\hldef{t.stat} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{further,}
                    \hlkwc{mu} \hldef{= mu0,}
                    \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{)}
\hldef{t.further} \hlkwb{<-} \hldef{t.stat}\hlopt{$}\hldef{statistic}

\hldef{n} \hlkwb{<-} \hlkwd{length}\hldef{(data}\hlopt{$}\hldef{further)}

\hldef{skewness} \hlkwb{<-} \hlkwd{skewness}\hldef{(data}\hlopt{$}\hldef{further)}
\hldef{fz} \hlkwb{<-} \hlkwd{dnorm}\hldef{(t.further)}
\hldef{Fz} \hlkwb{<-} \hlkwd{pnorm}\hldef{(t.further)}

\hldef{(edgeworth.error} \hlkwb{<-} \hldef{(skewness}\hlopt{/}\hlkwd{sqrt}\hldef{(n))} \hlopt{*} \hldef{(((}\hlnum{2}\hlopt{*}\hldef{(t.further)}\hlopt{^}\hlnum{2} \hlopt{+} \hlnum{1}\hldef{)}\hlopt{/}\hlnum{6}\hldef{)}\hlopt{*}\hldef{(fz)))}
\end{alltt}
\begin{verbatim}
##             t 
## -1.226006e-13
\end{verbatim}
\begin{alltt}
\hldef{(probability} \hlkwb{<-} \hldef{Fz} \hlopt{+} \hldef{edgeworth.error)}
\end{alltt}
\begin{verbatim}
##             t 
## -1.189164e-13
\end{verbatim}
\end{kframe}
\end{knitrout}

The probability is \ensuremath{-1.1891637\times 10^{-13}} and the Edgeworth approximation is \ensuremath{-1.2260063\times 10^{-13}}. As the value of the Edgeworth approximation is small, the t-test can be said to be \textbf{NOT} "far off".

  \item Compute the error for $t$ statistics from -10 to 10 and plot a line
  that shows the error across $t$. Continue to use the skewness and 
  the sample size for the zebra finch further data.
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{t.vals} \hlkwb{<-} \hlkwd{seq}\hldef{(}\hlopt{-}\hlnum{10}\hldef{,}\hlnum{10}\hldef{,} \hlkwc{length} \hldef{=} \hlnum{1000}\hldef{)}
\hldef{fzb} \hlkwb{<-} \hlkwd{dnorm}\hldef{(t.vals)}

\hldef{error.vals} \hlkwb{<-} \hldef{(skewness}\hlopt{/}\hlkwd{sqrt}\hldef{(n))} \hlopt{*} \hldef{(((}\hlnum{2}\hlopt{*}\hldef{(t.vals)}\hlopt{^}\hlnum{2} \hlopt{+} \hlnum{1}\hldef{)}\hlopt{/}\hlnum{6}\hldef{)}\hlopt{*}\hldef{(fzb))}

\hldef{tvals.error} \hlkwb{<-} \hlkwd{tibble}\hldef{(}
  \hlkwc{t} \hldef{= t.vals,}
  \hlkwc{error} \hldef{= error.vals}
\hldef{)}

\hlkwd{ggplot}\hldef{()}\hlopt{+}
  \hlkwd{geom_line}\hldef{(}\hlkwc{data} \hldef{= tvals.error,}
            \hlkwd{aes}\hldef{(}\hlkwc{x} \hldef{= t,} \hlkwc{y} \hldef{= error),}
            \hlkwc{color} \hldef{=} \hlsng{"red"}\hldef{)}\hlopt{+}
  \hlkwd{theme_bw}\hldef{()}\hlopt{+}
  \hlkwd{labs}\hldef{(}\hlkwc{title} \hldef{=} \hlsng{"Edgeworth Approximation For Error"}\hldef{,}
       \hlkwc{x} \hldef{=} \hlsng{"T Values (-10,10)"}\hldef{,}
       \hlkwc{y} \hldef{=} \hlsng{"Error"}\hldef{)}
\end{alltt}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-3-1} 
\end{knitrout}

The plot looks like a \textbf{W}. The plot shows that t values $<5$ and $>5$ are zero. The most error 

  \item Suppose we wanted to have a tail probability within 10\% of the desired
  $\alpha=0.05$. Recall we did a left-tailed test using the further data.
  How large of a sample size would we need? That is, we need
  to solve the error formula equal to 10\% of the desired left-tail probability:
  \[0.10 \alpha  \stackrel{set}{=} \underbrace{\frac{\text{skew}}{\sqrt{n}} \frac{(2t^2+1)}{6} f_Z(t)}_{\textrm{error}},\]
  which yields
  \[ n = \left(\frac{\text{skew}}{6(0.10\alpha)} (2t^2 + 1) f_Z(t)\right)^2.\]

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{val.t} \hlkwb{<-} \hlkwd{qnorm}\hldef{(}\hlnum{0.05}\hldef{)}
\hldef{fzc} \hlkwb{<-} \hlkwd{dnorm}\hldef{(val.t)}

\hldef{(n} \hlkwb{<-} \hldef{((skewness}\hlopt{/}\hldef{(}\hlnum{6}\hlopt{*}\hldef{(}\hlnum{0.10}\hlopt{*}\hlnum{0.05}\hldef{)))} \hlopt{*} \hldef{(}\hlnum{2}\hlopt{*}\hldef{val.t}\hlopt{^}\hlnum{2} \hlopt{+} \hlnum{1}\hldef{)} \hlopt{*}\hldef{fzc)}\hlopt{^}\hlnum{2}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 520.8876
\end{verbatim}
\end{kframe}
\end{knitrout}
The sample size needed to reach $\alpha = 0.05$ is 520.8876044. To reach 10\% of $\alpha = 0.05$, we will need a much larger sample than the 25 taken in the study.
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Complete the following steps to revisit the analyses from lab 11 using the
bootstrap procedure.
\begin{enumerate}
\item Now, consider the zebra finch data. We do not know the generating distributions
for the closer, further, and difference data, so perform resampling to approximate the 
sampling distribution of the $T$ statistic:
  \[T = \frac{\bar{x}_r - 0}{s/\sqrt{n}},\]
  where $\bar{x}_r$ is the mean computed on the r$^{th}$ resample and $s$ is the
  sample standard deviation from the original samples. At the end, create an
  object called \texttt{resamples.null.closer}, for example, and store the 
  resamples shifted to ensure they are consistent with the null hypotheses at the average 
  (i.e., here ensure the shifted resamples are 0 on average, corresponding
  to $t=0$, for each case).
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{R} \hlkwb{<-} \hlnum{10000}
\hldef{sd.closer} \hlkwb{<-} \hlkwd{sd}\hldef{(data}\hlopt{$}\hldef{closer)}
\hldef{num.closer} \hlkwb{<-} \hlkwd{length}\hldef{(data}\hlopt{$}\hldef{closer)}
\hldef{resamples.closer} \hlkwb{<-}  \hlkwd{tibble}\hldef{(}\hlkwc{tstat}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R),}
                            \hlkwc{xbar}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.resample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= data}\hlopt{$}\hldef{closer,}
                          \hlkwc{size} \hldef{= num.closer,}
                          \hlkwc{replace} \hldef{= T)}
  \hldef{resamples.closer}\hlopt{$}\hldef{tstat[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.resample)}\hlopt{-}\hlnum{0}\hldef{)}\hlopt{/}\hldef{(sd.closer}\hlopt{/}\hlkwd{sqrt}\hldef{(num.closer))}
  \hldef{resamples.closer}\hlopt{$}\hldef{xbar[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.resample)}
\hldef{\}}


\hldef{closer.delta} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.closer}\hlopt{$}\hldef{tstat)} \hlopt{-} \hlnum{0}

\hldef{resamples.null.closer} \hlkwb{<-} \hldef{resamples.closer |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{shifted} \hldef{= tstat} \hlopt{-} \hldef{closer.delta)}

\hldef{R} \hlkwb{<-} \hlnum{10000}
\hldef{sd.further} \hlkwb{<-} \hlkwd{sd}\hldef{(data}\hlopt{$}\hldef{further)}
\hldef{num.further} \hlkwb{<-} \hlkwd{length}\hldef{(data}\hlopt{$}\hldef{further)}
\hldef{resamples.further} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{tstat}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R),}
                            \hlkwc{xbar}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.resample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= data}\hlopt{$}\hldef{further,}
                          \hlkwc{size} \hldef{= num.further,}
                          \hlkwc{replace} \hldef{= T)}
  \hldef{resamples.further}\hlopt{$}\hldef{tstat[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.resample)}\hlopt{-}\hlnum{0}\hldef{)}\hlopt{/}\hldef{(sd.further}\hlopt{/}\hlkwd{sqrt}\hldef{(num.further))}
  \hldef{resamples.further}\hlopt{$}\hldef{xbar[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.resample)}
\hldef{\}}


\hldef{further.delta} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.further}\hlopt{$}\hldef{tstat)} \hlopt{-} \hlnum{0}

\hldef{resamples.null.further} \hlkwb{<-} \hldef{resamples.further |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{shifted} \hldef{= tstat} \hlopt{-} \hldef{further.delta)}

\hldef{R} \hlkwb{<-} \hlnum{10000}
\hldef{sd.diff} \hlkwb{<-} \hlkwd{sd}\hldef{(data}\hlopt{$}\hldef{diff)}
\hldef{num.diff} \hlkwb{<-} \hlkwd{length}\hldef{(data}\hlopt{$}\hldef{diff)}
\hldef{resamples.diff} \hlkwb{<-}  \hlkwd{tibble}\hldef{(}\hlkwc{tstat}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R),}
                          \hlkwc{xbar}\hldef{=}\hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}
\hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R)\{}
  \hldef{curr.resample} \hlkwb{<-} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{= data}\hlopt{$}\hldef{diff,}
                          \hlkwc{size} \hldef{= num.diff,}
                          \hlkwc{replace} \hldef{= T)}
  \hldef{resamples.diff}\hlopt{$}\hldef{tstat[i]} \hlkwb{<-} \hldef{(}\hlkwd{mean}\hldef{(curr.resample)}\hlopt{-}\hlnum{0}\hldef{)}\hlopt{/}\hldef{(sd.diff}\hlopt{/}\hlkwd{sqrt}\hldef{(num.diff))}
  \hldef{resamples.diff}\hlopt{$}\hldef{xbar[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.resample)}
\hldef{\}}

\hldef{diff.delta} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.diff}\hlopt{$}\hldef{tstat)} \hlopt{-} \hlnum{0}
\hldef{resamples.null.diff} \hlkwb{<-} \hldef{resamples.diff |>}
  \hlkwd{mutate}\hldef{(}\hlkwc{shifted} \hldef{= tstat} \hlopt{-} \hldef{diff.delta)}

\hldef{(}\hlkwd{mean}\hldef{(resamples.null.closer}\hlopt{$}\hldef{shifted))}
\end{alltt}
\begin{verbatim}
## [1] 1.514344e-16
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{mean}\hldef{(resamples.null.further}\hlopt{$}\hldef{shifted))}
\end{alltt}
\begin{verbatim}
## [1] 1.460165e-16
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{mean}\hldef{(resamples.null.diff}\hlopt{$}\hldef{shifted))}
\end{alltt}
\begin{verbatim}
## [1] 8.837708e-16
\end{verbatim}
\end{kframe}
\end{knitrout}

We tested to see whether the unknown distributions of closer, further, and difference are consistent with the null hypothesis at the average. We used resampling to approximate the distribution and then stored the shifted resamples. The closer shifted mean is \ensuremath{1.5143442\times 10^{-16}}, further shifted mean is \ensuremath{1.4601653\times 10^{-16}}, and the difference shifted mean is \ensuremath{8.8377083\times 10^{-16}}. All of these values are near zero which indicates that the resamples are consistent with the null.
 
  \item Compute the bootstrap $p$-value for each test using the shifted resamples. How do these compare to the $t$-test $p$-values?

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# T-Test P-Value}
\hldef{t.p.close} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{closer,}
                     \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                     \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}\hlopt{$}\hldef{p.value}

\hldef{t.p.further} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{further,}
                      \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                      \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{)}\hlopt{$}\hldef{p.value}

\hldef{t.p.diff} \hlkwb{<-} \hlkwd{t.test}\hldef{(data}\hlopt{$}\hldef{diff,}
                   \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                   \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}\hlopt{$}\hldef{p.value}

\hlcom{# Bootstrap P-Value}
\hldef{boot.p.closer} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.null.closer}\hlopt{$}\hldef{shifted} \hlopt{>=} \hldef{closer.delta)}

\hldef{boot.p.further} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.null.further}\hlopt{$}\hldef{shifted} \hlopt{<=} \hldef{further.delta)}

\hldef{low} \hlkwb{<-} \hlnum{0} \hlopt{-} \hldef{diff.delta}
\hldef{high} \hlkwb{<-} \hlnum{0} \hlopt{+} \hldef{diff.delta}
\hldef{p.low} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.null.diff}\hlopt{$}\hldef{shifted} \hlopt{<=} \hldef{low)}
\hldef{p.high} \hlkwb{<-} \hlkwd{mean}\hldef{(resamples.null.diff}\hlopt{$}\hldef{shifted} \hlopt{>=} \hldef{high)}
\hldef{boot.p.diff} \hlkwb{<-} \hldef{p.low} \hlopt{+} \hldef{p.high}

\hldef{(}\hlkwd{round}\hldef{(t.p.close,} \hlnum{4}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(boot.p.closer)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{round}\hldef{(t.p.further,} \hlnum{4}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(boot.p.further)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{round}\hldef{(t.p.diff,} \hlnum{4}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(boot.p.diff)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\end{kframe}
\end{knitrout}

As can be seen, both the T-Test P-Values and Bootstrap P-Values are all near zero and are represented as zero when rounded to four decimal places.

    \item What is the 5$^{th}$ percentile of the shifted resamples under the null hypothesis? 
  Note this value approximates $t_{0.05, n-1}$. Compare these values in each case.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{boot.closer.5th} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.closer}\hlopt{$}\hldef{shifted,} \hlnum{0.05}\hldef{)}
\hldef{t.closer.5th} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.05}\hldef{,} \hlkwc{df} \hldef{= num.closer} \hlopt{-}\hlnum{1}\hldef{)}

\hldef{boot.further.5th} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.further}\hlopt{$}\hldef{shifted,} \hlnum{0.05}\hldef{)}
\hldef{t.further.5th} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.05}\hldef{,} \hlkwc{df} \hldef{= num.further} \hlopt{-}\hlnum{1}\hldef{)}

\hldef{boot.diff.5th} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.diff}\hlopt{$}\hldef{shifted,} \hlnum{0.05}\hldef{)}
\hldef{t.diff.5th} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.05}\hldef{,} \hlkwc{df} \hldef{= num.diff} \hlopt{-}\hlnum{1}\hldef{)}

\hldef{(boot.closer.5th)}
\end{alltt}
\begin{verbatim}
##      5% 
## -1.6016
\end{verbatim}
\begin{alltt}
\hldef{(t.closer.5th)}
\end{alltt}
\begin{verbatim}
## [1] -1.710882
\end{verbatim}
\begin{alltt}
\hldef{(boot.further.5th)}
\end{alltt}
\begin{verbatim}
##        5% 
## -1.689314
\end{verbatim}
\begin{alltt}
\hldef{(t.further.5th)}
\end{alltt}
\begin{verbatim}
## [1] -1.710882
\end{verbatim}
\begin{alltt}
\hldef{(boot.diff.5th)}
\end{alltt}
\begin{verbatim}
##        5% 
## -1.551229
\end{verbatim}
\begin{alltt}
\hldef{(t.diff.5th)}
\end{alltt}
\begin{verbatim}
## [1] -1.710882
\end{verbatim}
\end{kframe}
\end{knitrout}

The bootstrapping $5^{th}$ percentile for the various cases are -1.6015998 for the close, -1.6893145 for the further, and -1.6893145 for the difference. The t-test $5^{th}$ percentile for the various cases are -1.7108821 for the close, -1.7108821 for the further, and -1.7108821 for the difference. As we can see, the bootstrapping and t-test $5^{th}$ percentiles are fairly similar to each other.

  \item Compute the bootstrap confidence intervals using the resamples. How do these 
  compare to the $t$-test confidence intervals?

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{boot.CI.closer} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.closer}\hlopt{$}\hldef{xbar,} \hlkwd{c}\hldef{(}\hlnum{0.025}\hldef{,} \hlnum{0.975}\hldef{))}
\hldef{t.CI.closer} \hlkwb{<-} \hlkwd{t.test}\hldef{(}\hlkwc{x}\hldef{=data}\hlopt{$}\hldef{closer,}
                      \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                      \hlkwc{conf.level} \hldef{=} \hlnum{0.95}\hldef{,}
                      \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}\hlopt{$}\hldef{conf.int}

\hldef{boot.CI.further} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.further}\hlopt{$}\hldef{xbar,} \hlkwd{c}\hldef{(}\hlnum{0.025}\hldef{,} \hlnum{0.975}\hldef{))}
\hldef{t.CI.further} \hlkwb{<-} \hlkwd{t.test}\hldef{(}\hlkwc{x}\hldef{=data}\hlopt{$}\hldef{further,}
                       \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                       \hlkwc{conf.level} \hldef{=} \hlnum{0.95}\hldef{,}
                       \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}\hlopt{$}\hldef{conf.int}

\hldef{boot.CI.diff} \hlkwb{<-} \hlkwd{quantile}\hldef{(resamples.null.diff}\hlopt{$}\hldef{xbar,} \hlkwd{c}\hldef{(}\hlnum{0.025}\hldef{,} \hlnum{0.975}\hldef{))}
\hldef{t.CI.diff} \hlkwb{<-} \hlkwd{t.test}\hldef{(}\hlkwc{x}\hldef{=data}\hlopt{$}\hldef{diff,}
                    \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                    \hlkwc{conf.level} \hldef{=} \hlnum{0.95}\hldef{,}
                    \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}\hlopt{$}\hldef{conf.int}

\hldef{(boot.CI.closer)}
\end{alltt}
\begin{verbatim}
##      2.5%     97.5% 
## 0.1201887 0.1926274
\end{verbatim}
\begin{alltt}
\hldef{(t.CI.closer)}
\end{alltt}
\begin{verbatim}
## [1] 0.1173875 0.1950586
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}
\begin{alltt}
\hldef{(boot.CI.further)}
\end{alltt}
\begin{verbatim}
##       2.5%      97.5% 
## -0.2551750 -0.1557434
\end{verbatim}
\begin{alltt}
\hldef{(t.CI.further)}
\end{alltt}
\begin{verbatim}
## [1] -0.2565176 -0.1489313
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}
\begin{alltt}
\hldef{(boot.CI.diff)}
\end{alltt}
\begin{verbatim}
##      2.5%     97.5% 
## 0.2810191 0.4414708
\end{verbatim}
\begin{alltt}
\hldef{(t.CI.diff)}
\end{alltt}
\begin{verbatim}
## [1] 0.2719028 0.4459921
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}
\end{kframe}
\end{knitrout}

As can be seen, the confidence intervals for each case are fairly similar between the bootstrap and t-test and do not differ by a large value.
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 3
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item Complete the following steps to revisit the analyses from lab 11 using the
randomization procedure.
\begin{enumerate}
\item Now, consider the zebra finch data. We do not know the generating distributions
for the closer, further, and difference data, so perform the randomization procedure

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{randomization.dist} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{data}\hldef{,} \hlkwc{mu0}\hldef{,} \hlkwc{R} \hldef{=} \hlnum{10000}\hldef{) \{}
  \hldef{random} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{means} \hldef{=} \hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}

  \hldef{shifted.data} \hlkwb{<-} \hldef{data} \hlopt{-} \hldef{mu0}

  \hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R) \{}
    \hldef{curr.random} \hlkwb{<-} \hldef{shifted.data} \hlopt{*} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{=} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{1}\hldef{,} \hlnum{1}\hldef{),}
                                         \hlkwc{size} \hldef{=} \hlkwd{length}\hldef{(shifted.data),}
                                         \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
    \hldef{random}\hlopt{$}\hldef{means[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.random)}
  \hldef{\}}

  \hldef{random} \hlkwb{<-} \hldef{random |>}
    \hlkwd{mutate}\hldef{(}\hlkwc{means} \hldef{= means} \hlopt{+} \hldef{mu0)}

  \hlkwd{return}\hldef{(random)}
\hldef{\}}

\hldef{closer.rand} \hlkwb{<-} \hlkwd{randomization.dist}\hldef{(data}\hlopt{$}\hldef{closer,} \hlnum{0}\hldef{)}
\hldef{farther.rand} \hlkwb{<-} \hlkwd{randomization.dist}\hldef{(data}\hlopt{$}\hldef{further,} \hlnum{0}\hldef{)}
\hldef{diff.rand} \hlkwb{<-} \hlkwd{randomization.dist}\hldef{(data}\hlopt{$}\hldef{diff,} \hlnum{0}\hldef{)}

\hldef{(}\hlkwd{mean}\hldef{(closer.rand}\hlopt{$}\hldef{means))}
\end{alltt}
\begin{verbatim}
## [1] 0.0003950941
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{mean}\hldef{(farther.rand}\hlopt{$}\hldef{means))}
\end{alltt}
\begin{verbatim}
## [1] 0.0003820186
\end{verbatim}
\begin{alltt}
\hldef{(}\hlkwd{mean}\hldef{(diff.rand}\hlopt{$}\hldef{means))}
\end{alltt}
\begin{verbatim}
## [1] -0.0001880823
\end{verbatim}
\end{kframe}
\end{knitrout}

In this step, we found representative distribution for each case. As can be seen, each of the randomized distributions has a mean of about zero.

  \item Compute the randomization test $p$-value for each test.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{closer.mean} \hlkwb{<-} \hlkwd{mean}\hldef{(data}\hlopt{$}\hldef{closer)}
\hldef{closer.p.random} \hlkwb{<-} \hlkwd{mean}\hldef{(closer.rand}\hlopt{$}\hldef{means} \hlopt{>=} \hldef{closer.mean)}

\hldef{further.mean} \hlkwb{<-} \hlkwd{mean}\hldef{(data}\hlopt{$}\hldef{further)}
\hldef{further.p.random} \hlkwb{<-} \hlkwd{mean}\hldef{(farther.rand}\hlopt{$}\hldef{means} \hlopt{<=} \hldef{further.mean)}

\hldef{diff.delta} \hlkwb{<-} \hlkwd{abs}\hldef{(}\hlkwd{mean}\hldef{(data}\hlopt{$}\hldef{diff)} \hlopt{-} \hldef{mu0)}
\hldef{mirror} \hlkwb{<-} \hldef{mu0} \hlopt{-} \hldef{diff.delta}
\hldef{xbar} \hlkwb{<-} \hldef{mu0} \hlopt{+} \hldef{diff.delta}

\hldef{diff.p.random} \hlkwb{<-} \hlkwd{mean}\hldef{(diff.rand}\hlopt{$}\hldef{means} \hlopt{<=} \hldef{mirror)} \hlopt{+}
                 \hlkwd{mean}\hldef{(diff.rand}\hlopt{$}\hldef{means} \hlopt{>=} \hldef{xbar)}

\hldef{(closer.p.random)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(further.p.random)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\begin{alltt}
\hldef{(diff.p.random)}
\end{alltt}
\begin{verbatim}
## [1] 0
\end{verbatim}
\end{kframe}
\end{knitrout}

All the p-values are zero which means there is statistically discernible support for the alternative hypothesis. The p-value of zero suggests that the observed mean is in the right tail for close, left tail for further, and in both tails for the difference.
  \item Compute the randomization confidence interval by iterating over values of $\mu_0$.\\
  \textbf{Hint:} You can ``search" for the lower bound from $Q_1$ and subtracting by 0.0001, 
  and the upper bound using $Q_3$ and increasing by 0.0001. You will continue until you find 
  the first value for which the two-sided $p$-value is greater than or equal to 0.05.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{CI.finder} \hlkwb{<-} \hlkwa{function}\hldef{(}\hlkwc{data}\hldef{,} \hlkwc{R} \hldef{=} \hlnum{1000}\hldef{)\{}

  \hldef{mu0.iter} \hlkwb{<-} \hlnum{0.01}
  \hldef{mu0.lower} \hlkwb{<-} \hlkwd{mean}\hldef{(data)}
  \hldef{mu0.higher} \hlkwb{<-} \hlkwd{mean}\hldef{(data)}

  \hlkwa{repeat}\hldef{\{}
    \hldef{random} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{means} \hldef{=} \hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}

    \hldef{shifted.data} \hlkwb{<-} \hldef{data} \hlopt{-} \hldef{mu0.lower}

    \hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R) \{}
      \hldef{curr.random} \hlkwb{<-} \hldef{shifted.data} \hlopt{*} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{=} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{1}\hldef{,} \hlnum{1}\hldef{),}
                                           \hlkwc{size} \hldef{=} \hlkwd{length}\hldef{(shifted.data),}
                                           \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
      \hldef{random}\hlopt{$}\hldef{means[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.random)}
    \hldef{\}}

    \hldef{random} \hlkwb{<-} \hldef{random |>}
      \hlkwd{mutate}\hldef{(}\hlkwc{means} \hldef{= means} \hlopt{+} \hldef{mu0.lower)}

    \hldef{delta} \hlkwb{<-} \hlkwd{abs}\hldef{(}\hlkwd{mean}\hldef{(data)} \hlopt{-} \hldef{mu0.lower)}
    \hldef{low} \hlkwb{<-} \hldef{mu0.lower} \hlopt{-} \hldef{delta}
    \hldef{high} \hlkwb{<-} \hldef{mu0.lower} \hlopt{+} \hldef{delta}
    \hldef{p.val} \hlkwb{<-} \hlkwd{mean}\hldef{(random}\hlopt{$}\hldef{means} \hlopt{<=} \hldef{low)} \hlopt{+}
             \hlkwd{mean}\hldef{(random}\hlopt{$}\hldef{means} \hlopt{>=} \hldef{high)}

    \hlkwa{if}\hldef{(p.val} \hlopt{<} \hlnum{0.05}\hldef{)\{}
      \hlkwa{break}
    \hldef{\}}\hlkwa{else}\hldef{\{}
      \hldef{mu0.lower} \hlkwb{<-} \hldef{mu0.lower} \hlopt{-} \hldef{mu0.iter}
    \hldef{\}}
  \hldef{\}}

  \hlkwa{repeat}\hldef{\{}
    \hldef{random} \hlkwb{<-} \hlkwd{tibble}\hldef{(}\hlkwc{means} \hldef{=} \hlkwd{rep}\hldef{(}\hlnum{NA}\hldef{, R))}

    \hldef{shifted.data} \hlkwb{<-} \hldef{data} \hlopt{-} \hldef{mu0.higher}

    \hlkwa{for}\hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hldef{R) \{}
      \hldef{curr.random} \hlkwb{<-} \hldef{shifted.data} \hlopt{*} \hlkwd{sample}\hldef{(}\hlkwc{x} \hldef{=} \hlkwd{c}\hldef{(}\hlopt{-}\hlnum{1}\hldef{,} \hlnum{1}\hldef{),}
                                           \hlkwc{size} \hldef{=} \hlkwd{length}\hldef{(shifted.data),}
                                           \hlkwc{replace} \hldef{=} \hlnum{TRUE}\hldef{)}
      \hldef{random}\hlopt{$}\hldef{means[i]} \hlkwb{<-} \hlkwd{mean}\hldef{(curr.random)}
    \hldef{\}}

    \hldef{random} \hlkwb{<-} \hldef{random |>}
      \hlkwd{mutate}\hldef{(}\hlkwc{means} \hldef{= means} \hlopt{+} \hldef{mu0.higher)}

    \hldef{delta} \hlkwb{<-} \hlkwd{abs}\hldef{(}\hlkwd{mean}\hldef{(data)} \hlopt{-} \hldef{mu0.higher)}
    \hldef{low} \hlkwb{<-} \hldef{mu0.higher} \hlopt{-} \hldef{delta}
    \hldef{high} \hlkwb{<-} \hldef{mu0.higher} \hlopt{+} \hldef{delta}
    \hldef{p.val} \hlkwb{<-} \hlkwd{mean}\hldef{(random}\hlopt{$}\hldef{means} \hlopt{<=} \hldef{low)} \hlopt{+}
      \hlkwd{mean}\hldef{(random}\hlopt{$}\hldef{means} \hlopt{>=} \hldef{high)}

    \hlkwa{if}\hldef{(p.val} \hlopt{<} \hlnum{0.05}\hldef{)\{}
      \hlkwa{break}
    \hldef{\}}\hlkwa{else}\hldef{\{}
      \hldef{mu0.higher} \hlkwb{<-} \hldef{mu0.higher} \hlopt{+} \hldef{mu0.iter}
    \hldef{\}}
  \hldef{\}}

  \hlkwd{return}\hldef{(}\hlkwd{c}\hldef{(mu0.lower, mu0.higher))}
\hldef{\}}

\hldef{(close.CI.randomization} \hlkwb{<-} \hlkwd{CI.finder}\hldef{(data}\hlopt{$}\hldef{closer))}
\end{alltt}
\begin{verbatim}
## [1] 0.1062231 0.1962231
\end{verbatim}
\begin{alltt}
\hldef{(further.CI.randomization} \hlkwb{<-} \hlkwd{CI.finder}\hldef{(data}\hlopt{$}\hldef{further))}
\end{alltt}
\begin{verbatim}
## [1] -0.2627244 -0.1427244
\end{verbatim}
\begin{alltt}
\hldef{(diff.CI.randomization} \hlkwb{<-} \hlkwd{CI.finder}\hldef{(data}\hlopt{$}\hldef{diff))}
\end{alltt}
\begin{verbatim}
## [1] 0.2589475 0.4489475
\end{verbatim}
\end{kframe}
\end{knitrout}

The confidence intervals are (0.1062231, 0.1962231) for close, (-0.2627244, -0.1427244) for further, and (0.2589475, 0.4489475) for difference. These values are similar to those found earlier in the bootstrap and t-test methods.

\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Optional Question
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item \textbf{Optional Challenge:} In this lab, you performed resampling to 
approximate the sampling distribution of the $T$ statistic using
\[T = \frac{\bar{x}_r - 0}{s/\sqrt{n}}.\]
I'm curious whether it is better/worse/similar if we computed the statistics
using the sample standard deviation of the resamples ($s_r$), instead of the 
original sample ($s$)
  \[T = \frac{\bar{x}_r - 0}{s_r/\sqrt{n}}.\]
\begin{enumerate}
  \item Perform a simulation study to evaluate the Type I error for conducting this
hypothesis test both ways.
  \item Using the same test case(s) as part (a), compute bootstrap confidence 
  intervals and assess their coverage -- how often do we `capture' the parameter
of interest?
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}

